POST http://localhost:3000/api/login
Content-Type:  application/json

{
    "phone":"1",
    "password":"bedatnee312"
}


###
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjczOTcyNzksImV4cCI6MTY2NzQ0MDQ3OX0.E0ukxmTG2W7zkckUOPVfUwHfmHxBvwSbfkAFOYm2LoE


GET http://localhost:3000/api/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjczOTc0NjcsImV4cCI6MTY2NzQ0MDY2N30.fPJfWsHPaLsp3Ujb7ISM-St5HG9KM5vIvBBaIZHbUeQ

###
GET http://localhost:3000/api/product?productId=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjczOTc0NjcsImV4cCI6MTY2NzQ0MDY2N30.fPJfWsHPaLsp3Ujb7ISM-St5HG9KM5vIvBBaIZHbUeQ

###
GET http://localhost:3000/api/product?productId=9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ODYyNDkwMjIiLCJpYXQiOjE2NjgwNzA5NzQsImV4cCI6MTY2ODExNDE3NH0.sZbgNTNzRitkE-7dR_SXeAqUq3MkBUkkYqatbR1ojFI

###
POST http://localhost:3000/api/product/value
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ODYyNDkwMjIiLCJpYXQiOjE2NjgwNzA5NzQsImV4cCI6MTY2ODExNDE3NH0.sZbgNTNzRitkE-7dR_SXeAqUq3MkBUkkYqatbR1ojFI

{
    "slug":"ao-khoac-jean-denim-caro-nam-unisex-form-rong-basic-ao-khoat-jacket-jean-nam-nu-caro-phong-cach-djuong-pho-1077",
    "skuValues": [
        {
            "price":550000,
            "qty":5000,
            "discount":36,
            "image":"https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
            "values":[
                        {
                            "id": 20,
                            "name": "Xám",
                            "variantId": 11,
                            "productId": 9,
                            "variant": {
                            "id": 11,
                            "name": "Màu",
                            "productId": 9
                            }
                        },
                        {
                            "id": 21,
                            "name": "L",
                            "variantId": 12,
                            "productId": 9,
                            "variant": {
                            "id": 12,
                            "name": "Size",
                            "productId": 9
                            }
                        }
                    ]
        },
        {
            "price":550000,
            "qty":4560,
            "discount":40,
            "image":"https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
            "values":[
                                    {
                    "id": 20,
                    "name": "Xám",
                    "variantId": 11,
                    "productId": 9,
                    "variant": {
                    "id": 11,
                    "name": "Màu",
                    "productId": 9
                    }
                },
                {
                    "id": 23,
                    "name": "XL",
                    "variantId": 12,
                    "productId": 9,
                    "variant": {
                    "id": 12,
                    "name": "Size",
                    "productId": 9
                    }
                }
                    ]
        },
        {
            "price":550000,
            "qty":3456,
            "discount":23,
            "image":"https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
            "values":[
                       {
        "id": 20,
        "name": "Xám",
        "variantId": 11,
        "productId": 9,
        "variant": {
          "id": 11,
          "name": "Màu",
          "productId": 9
        }
      },
      {
        "id": 24,
        "name": "M",
        "variantId": 12,
        "productId": 9,
        "variant": {
          "id": 12,
          "name": "Size",
          "productId": 9
        }
      }
                    ]
        },
        {
            "price":550000,
            "qty":5000,
            "discount":36,
            "image":"https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
            "values":[
                        {
        "id": 22,
        "name": "Đen",
        "variantId": 11,
        "productId": 9,
        "variant": {
          "id": 11,
          "name": "Màu",
          "productId": 9
        }
      },
      {
        "id": 21,
        "name": "L",
        "variantId": 12,
        "productId": 9,
        "variant": {
          "id": 12,
          "name": "Size",
          "productId": 9
        }
      }
                    ]
        },
        {
            "price":450000,
            "qty":5700,
            "discount":10,
            "image":"https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
            "values":[
                        {
        "id": 22,
        "name": "Đen",
        "variantId": 11,
        "productId": 9,
        "variant": {
          "id": 11,
          "name": "Màu",
          "productId": 9
        }
      },
      {
        "id": 23,
        "name": "XL",
        "variantId": 12,
        "productId": 9,
        "variant": {
          "id": 12,
          "name": "Size",
          "productId": 9
        }
      }
                    ]
        },
        {
            "price":550000,
            "qty":4500,
            "discount":36,
            "image":"https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
            "values":[
                        {
        "id": 22,
        "name": "Đen",
        "variantId": 11,
        "productId": 9,
        "variant": {
          "id": 11,
          "name": "Màu",
          "productId": 9
        }
      },
      {
        "id": 24,
        "name": "M",
        "variantId": 12,
        "productId": 9,
        "variant": {
          "id": 12,
          "name": "Size",
          "productId": 9
        }
      }
                    ]
        }
    ]
}


###
POST http://localhost:3000/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ODYyNDkwMjIiLCJpYXQiOjE2NjgwNzQ3OTMsImV4cCI6MTY2ODExNzk5M30.SF12tnbTIFU1zOk2XcHMbzKeHKOXUG6CCjiXxgBrKr4

{
  "categoryId": 1,
  "name": "Áo khoác jean denim caro nam unisex form rộng basic, áo khoát jacket jean nam nữ caro phong cách đường phố 1077",
  "description":"áo khoác jean, áo khoát jean HÀNG CÓ SẴN #aokhoacjean #aokhoatjean Áo khoác jean denim caro nam unisex form rộng basic, áo khoát jacket jean nam nữ caro phong cách đường phố Hàng có sẵn nên shop có thể giao ngay ạ",
  "image": "https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
  "variants": [
    {
      "name": "Màu",
      "children": [{ "name": "Đen" }, { "name": "Xám" }]
    },
    {
        "name":"Size",
        "children":[{"name":"M"},{"name":"L"},{"name":"XL"}]
    }
  ]
}

###

GET http://localhost:3000/api/product/view?page=2&limit=1
Content-Type: application/json

###
DELETE http://localhost:3000/api/product/sku?skuId=24&permission=admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2Njc0MDQ5MjgsImV4cCI6MTY2NzQ0ODEyOH0.EWwIPBMSP7isNBeDAfMZwr6JB-7oGulisidd5jvsKJI

###

GET http://localhost:3000/api/product/filter?categoryId=1
Content-Type: application/json

###
POST http://localhost:3000/api/order/status
Content-Type: application/json

{
    "name":"Chờ xác nhận"
}

###
GET http://localhost:3000/api/product/detail?slug=day-djeo-djong-ho-chat-lieu-da-bo-that-100percent-thich-hop-cho-apple-watch-7-6-se-5-4-42mm-3
Content-Type: application/json

###
GET http://localhost:3000/api/login-social
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ODYyNDkwMjIiLCJpYXQiOjE2Njc5ODE0NzIsImV4cCI6MTY2ODAyNDY3Mn0.9vpkyomtsVi-kKhvkyLOTAO-b2XKz044HuRiBARnm6o
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsOXV6Nm1iZzAwMDI3azJrMm04bTVhem0iLCJuYW1lIjoixJDhuqF0IFRow6BuaCIsImVtYWlsIjoibHlkYXRsdGRAZ21haWwuY29tIiwiaXNBY3RpdmUiOnRydWUsInBob25lIjpudWxsLCJwYXNzd29yZCI6bnVsbCwibmFtZVNob3AiOm51bGwsImdlbmRlciI6bnVsbCwiZGF0ZSI6bnVsbCwicGVySWQiOjEsImVtYWlsVmVyaWZpZWQiOm51bGwsImltYWdlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUxtNXd1MjZ1VlEzZ2gyMDAzX1YyWHhYcmF3dmRvR2pudWNYOU1lNnNLQ2g9czk2LWMiLCJpYXQiOjE2Njc1NDkxNjR9.qyiTWaGPVIBZsjd5_TiTwTErb4GRAKq5uGp57B-vzDI"
}

###
POST http://localhost:3000/api/category?permission=admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ODYyNDkwMjIiLCJpYXQiOjE2Njc5ODE0NzIsImV4cCI6MTY2ODAyNDY3Mn0.9vpkyomtsVi-kKhvkyLOTAO-b2XKz044HuRiBARnm6o

{
    "name":"Điện thoại & phụ kiện",
    "image":"https://cf.shopee.vn/file/31234a27876fb89cd522d7e3db1ba5ca_tn"
}