POST http://localhost:3000/api/login
Content-Type:  application/json

{
    "phone":"0123456789",
    "password":"bedatnee312"
}


###
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjczOTcyNzksImV4cCI6MTY2NzQ0MDQ3OX0.E0ukxmTG2W7zkckUOPVfUwHfmHxBvwSbfkAFOYm2LoE


GET http://localhost:3000/api/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjczOTc0NjcsImV4cCI6MTY2NzQ0MDY2N30.fPJfWsHPaLsp3Ujb7ISM-St5HG9KM5vIvBBaIZHbUeQ

###
GET http://localhost:3000/api/product?productId=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2NjczOTc0NjcsImV4cCI6MTY2NzQ0MDY2N30.fPJfWsHPaLsp3Ujb7ISM-St5HG9KM5vIvBBaIZHbUeQ

###
GET http://localhost:3000/api/product?productId=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsOXV6Nm1iZzAwMDI3azJrMm04bTVhem0iLCJpYXQiOjE2Njg4NzM2MDUsImV4cCI6MTY2ODkxNjgwNX0.PH0d8IKIv4Wzh1G3MD8Hp6DVt8K8MxqcXaSCmnz0vWQ

###
POST http://localhost:3000/api/product/value
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsOXV6Nm1iZzAwMDI3azJrMm04bTVhem0iLCJpYXQiOjE2Njg4NzM2MDUsImV4cCI6MTY2ODkxNjgwNX0.PH0d8IKIv4Wzh1G3MD8Hp6DVt8K8MxqcXaSCmnz0vWQ

{
    "slug":"chuot-ko-day-bluetooth-2.4ghz-tu-sac-pin-cao-cap-2-trong-1-chong-on-dung-cho-djtmay-tinhlaptoplaptop-tao",
    "skuValues": [
        {
            "price":149000,
            "qty":124,
            "discount":34,
            "image":"https://cf.shopee.vn/file/94f96b48d787e9258e0f533d03a410b3",
            "values":[
                        {
                          "id": 25,
                          "name": "Xám",
                          "variantId": 13,
                          "productId": 10,
                          "variant": {
                            "id": 13,
                            "name": "Màu",
                            "productId": 10
                          }
                        }
                    ]
        },
        {
            "price":150000,
            "qty":123,
            "discount":34,
            "image":"https://cf.shopee.vn/file/7bda47cfcd5a5907d638b3f7f09e5213",
            "values":[
                                  {
                      "id": 26,
                      "name": "Đen",
                      "variantId": 13,
                      "productId": 10,
                      "variant": {
                        "id": 13,
                        "name": "Màu",
                        "productId": 10
                      }
                    }
                    ]
        },
        {
            "price":149000,
            "qty":120,
            "discount":34,
            "image":"https://cf.shopee.vn/file/sg-11134201-22100-eigw4ikj5eiv76",
            "values":[
                      {
              "id": 27,
              "name": "Trắng",
              "variantId": 13,
              "productId": 10,
              "variant": {
                "id": 13,
                "name": "Màu",
                "productId": 10
              }
            }
                    ]
        },
        {
            "price":151000,
            "qty":5000,
            "discount":34,
            "image":"https://cf.shopee.vn/file/db8bcb16c7a34de025d019075027deea",
            "values":[
                        {
      "id": 28,
      "name": "Vàng",
      "variantId": 13,
      "productId": 10,
      "variant": {
        "id": 13,
        "name": "Màu",
        "productId": 10
      }
    }
                    ]
        }
        
    ]
}


###
POST http://localhost:3000/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsOXV6Nm1iZzAwMDI3azJrMm04bTVhem0iLCJpYXQiOjE2Njg4NzM2MDUsImV4cCI6MTY2ODkxNjgwNX0.PH0d8IKIv4Wzh1G3MD8Hp6DVt8K8MxqcXaSCmnz0vWQ

{
  "categoryId": 2,
  "name": "Chuột ko dây Bluetooth 2.4Ghz tự sạc pin cao cấp 2 trong 1 chống ồn dùng cho ĐT,Máy Tính,Laptop,laptop táo",
  "description":"Được thiết kế đơn giản, hiện đại, màu sắc trang nhã với kích thước phù hợp với cả người dùng là nam hay nữ. Chất liệu ABS cao cấp có khả năng chống va đập rơi vỡ, đảm bảo độ bền cho chuột. ",
  "image": "https://cf.shopee.vn/file/7bda47cfcd5a5907d638b3f7f09e5213",
  "variants": [
    {
      "name": "Màu",
      "children": [{ "name": "Đen" }, { "name": "Trắng" }, { "name": "Xám" },{"name":"Vàng"}]
    }
  ]
}

###

GET http://localhost:3000/api/product/view?page=2&limit=1
Content-Type: application/json

###
DELETE http://localhost:3000/api/product/sku?skuId=24&permission=admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE2Njc0MDQ5MjgsImV4cCI6MTY2NzQ0ODEyOH0.EWwIPBMSP7isNBeDAfMZwr6JB-7oGulisidd5jvsKJI

###

GET http://localhost:3000/api/product/filter?categoryId=1
Content-Type: application/json

###
POST http://localhost:3000/api/order/status
Content-Type: application/json

{
    "name":"Chờ xác nhận"
}

###
GET http://localhost:3000/api/product/detail?slug=day-djeo-djong-ho-chat-lieu-da-bo-that-100percent-thich-hop-cho-apple-watch-7-6-se-5-4-42mm-3
Content-Type: application/json

###
GET http://localhost:3000/api/login-social
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ODYyNDkwMjIiLCJpYXQiOjE2Njc5ODE0NzIsImV4cCI6MTY2ODAyNDY3Mn0.9vpkyomtsVi-kKhvkyLOTAO-b2XKz044HuRiBARnm6o
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsOXV6Nm1iZzAwMDI3azJrMm04bTVhem0iLCJuYW1lIjoixJDhuqF0IFRow6BuaCIsImVtYWlsIjoibHlkYXRsdGRAZ21haWwuY29tIiwiaXNBY3RpdmUiOnRydWUsInBob25lIjpudWxsLCJwYXNzd29yZCI6bnVsbCwibmFtZVNob3AiOm51bGwsImdlbmRlciI6bnVsbCwiZGF0ZSI6bnVsbCwicGVySWQiOjEsImVtYWlsVmVyaWZpZWQiOm51bGwsImltYWdlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUxtNXd1MjZ1VlEzZ2gyMDAzX1YyWHhYcmF3dmRvR2pudWNYOU1lNnNLQ2g9czk2LWMiLCJpYXQiOjE2Njc1NDkxNjR9.qyiTWaGPVIBZsjd5_TiTwTErb4GRAKq5uGp57B-vzDI"
}

###
POST http://localhost:3000/api/category?permission=admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ODYyNDkwMjIiLCJpYXQiOjE2Njc5ODE0NzIsImV4cCI6MTY2ODAyNDY3Mn0.9vpkyomtsVi-kKhvkyLOTAO-b2XKz044HuRiBARnm6o

{
    "name":"Điện thoại & phụ kiện",
    "image":"https://cf.shopee.vn/file/31234a27876fb89cd522d7e3db1ba5ca_tn"
}


###
POST http://localhost:3000/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsYWQ4OWQ5aTAwMDByZ2gwOW0xdTV1N2IiLCJpYXQiOjE2NjgyMTUyMDUsImV4cCI6MTY2ODI1ODQwNX0.-Hxa6rWr8Wu_ugQcBmh5x6JmDnd9DlXPPpCAVxE0lOw

{
  "content":"Áo mặc quá chuẩn form!!",
  "pointStar":5,
  "productId":5,
  "images":["https://cf.shopee.vn/file/92e22ea754c54e8acd305b1f70087cbe_tn","https://cf.shopee.vn/file/92e22ea754c54e8acd305b1f70087cbe_tn"]
}

###
GET http://localhost:3000/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsYWQ4OWQ5aTAwMDByZ2gwOW0xdTV1N2IiLCJpYXQiOjE2NjgzNDY0NTgsImV4cCI6MTY2ODM4OTY1OH0.qddBnA2Bn8EiGjKoUlshZLU7kQYVRg51OtPpBijapRY

###
GET http://localhost:3000/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsYTE5YmY2czAwMDA3azB3ZXNxeWF4cnMiLCJpYXQiOjE2Njk3MzMyMzUsImV4cCI6MTY2OTc3NjQzNX0.i3mCcHSr8R28jSbR585EGia_RamLEQxQXTdJ8wBsjHs

###
GET http://localhost:3000/api/sku
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsOXV6Nm1iZzAwMDI3azJrMm04bTVhem0iLCJpYXQiOjE2NzAwNzUwMzQsImV4cCI6MTY3MDExODIzNH0.5lwhCP-dOLtm47-ZwuVGxRIyF0ANCO2Dtxk9Yd2G8-c