import { getCookie } from "cookies-next";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import AuthLayout from "../components/Layouts/AuthLayout";
import MainLayout from "../components/Layouts/MainLayout";
import FullLoading from "../components/Loading/FullLoading";
import Section1 from "../components/Sections/Section1";
import SectionMain from "../components/Sections/SectionMain";
import Slider from "../components/Slider";
import { CategoryModel } from "../models/category.model";
import { ProductModel, Products } from "../models/product.model";
import CategoryApi from "../services/category";
import ProductApi from "../services/product";

type HomeProps = {
  token?: string;
  categories: CategoryModel[];
  products: Products;
};

const Home: NextPage<HomeProps> = ({ token, categories, products }) => {
  console.log(categories);
  console.log(products);
  return (
    <>
      <Head>
        <title>
          Shopee Việt Nam | Mua và Bán Trên Ứng Dụng Di Động Hoặc Website
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthLayout token={token}>
        <MainLayout>
          <Slider />
          <Section1 data={categories} />
          <SectionMain data={products} />
        </MainLayout>
      </AuthLayout>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const token = req.cookies["token"];
  const data = await Promise.all([
    CategoryApi.getCategory(),
    ProductApi.home(),
  ]);

  if (token) {
    return {
      props: {
        token,
        categories: data[0],
        products: data[1],
      },
    };
  }

  // const data = await Promise.all([CategoryApi.getCategory]);
  // console.log(data);

  return {
    props: {
      categories: data[0],
      products: data[1],
    },
  };
};
